SERVER_IP = 'localhost'
CONTROLLER_QUEUE = 'controller-queue'
DB_HOST = 'localhost'
DB_USER = 'root'
DB_PASS = ''
DB_NAME = 'trab_final_sd'
SOCKET_PORT = 5000
SOCKET_HOST = '127.0.0.1'
HEALTHCHECK_INTERVAL = 10
SUPPRESS_LOG_LISTENER = ['healthcheck', 'ping_healthcheck']
SUPPRESS_LOG_SENDER = ['healthcheck', 'ping_healthcheck', 'kill']
SUPPRESS_LOG_TASK = ['healthcheck']
SUPPRESS_SQL = True
