SERVER_IP = 'localhost'
FRONTEND_QUEUE = 'frontend-queue'
CONTROLLER_QUEUE = 'controller-queue'
CONTROLLER_QUEUE = 'controller-queue'
DB_USER = 'root'
DB_PASS = ''
DB_NAME = 'trab_final_sd'
HEALTHCHECK_INTERVAL = 5
SUPPRESS_LOG_LISTENER = ['healthcheck', 'ping_healthcheck']
SUPPRESS_LOG_SENDER = ['healthcheck', 'ping_healthcheck', 'kill']
SUPPRESS_LOG_TASK = ['healthcheck']
SUPPRESS_SQL = True
