#SERVER_IP = 'localhost'
SERVER_IP = '18.191.149.251'
# RABBIT_HOST = 'rabbit'
RABBIT_HOST = '18.191.149.251'
# DB_HOST = 'mysql'
DB_HOST = 'ec2-18-191-149-251.us-east-2.compute.amazonaws.com'
FRONTEND_QUEUE = 'frontend-queue'
CONTROLLER_QUEUE = 'controller-queue'
CONTROLLER_QUEUE = 'controller-queue'
DB_USER = 'root'
DB_PASS = 'admin'
DB_NAME = 'trab_final_sd'
HEALTHCHECK_INTERVAL = 60
SUPPRESS_LOG_LISTENER = ['healthcheck', 'ping_healthcheck']
SUPPRESS_LOG_SENDER = ['healthcheck', 'ping_healthcheck', 'kill']
SUPPRESS_LOG_TASK = ['healthcheck']
SUPPRESS_SQL = True
SOCKET_PORT = 1234
